- job:
    name: ara-web-unit-tests
    parent: nodejs-npm
    description: Run unit tests
    files:
      - src/.*
      - public/.*
      - package.json
      - package-lock.json
      - .zuul.yaml
      - zuul-playbooks/.*
    vars:
      node_version: 10
    run: zuul-playbooks/test.yaml

- job:
    name: ara-web-build-dashboard
    # https://zuul.openstack.org/job/build-javascript-content
    parent: build-javascript-content
    description: |
      Uses a Ubuntu Xenial VM with Node 8 to run "npm run build" and make the
      results available for browsing during code review on review.opendev.org.
      It sets the homepage parameter from package.json to the URL where logs will
      be uploaded and configures the API server to api.demo.recordsansible.org.
    success-url: 'npm/html/'
    files:
      - src/.*
      - public/.*
      - package.json
      - package-lock.json
      - .zuul.yaml
      - zuul-playbooks/.*
    vars:
      node_version: 10
      npm_command: build
      javascript_content_dir: build
    pre-run: zuul-playbooks/pre.yaml
    run: zuul-playbooks/build-dashboard.yaml

- secret:
    name: ara_web_git_mirror_credentials
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - f7FZeb4otv9UAdU+XuJ27wppJYiRu7JUBkU+V6vYxnvDQPR2cgvbA1Qw2qWOBzj2kh+x9
          vrf6Uyx9+PX6RDbdajTE+tUr76Ztif72QLfotPVZ5rhLJUGWSlBC28mVTHbHEbON0d5Ne
          yhHbg6Ka1IgnEvaIg9HCNx8ktnLLa+NC27zUjXPlRWm6TxBRyg8T6M1XPHd7sOrpe4pRK
          cmJi72SgMDCwhKpcTnsH8zSIxIRKQ0u7YH5ABjiS0BGQ8/Wi2F4+mAzoG4M9cBfXjjBBf
          51231d4/eA2st86NGCE+kqhZj3Q9/nltiDiuWoLk8y81NWV2bcpvrDbtM3PI/Roz9Fq9c
          S4ICvc+yShKuMT1knDnLyOPIAzc5TEn884dZ0XP1QqaCu5/0mT22HeIY7iBtNpXzj7uOl
          7/pb4oqvG1hHNxeVwbNJVrHGmX7l9IFJm3bcfm8ZOc31uyWNz5/3rlNIsWz/8QWOp63V0
          FDh9PD6l5Mj7fhmAFaa7gRUKDO/4bwKqITuc6U3D7/9x7vjKAIuYAItNols6QrAmmwAC3
          V0eulzQ+ree4gAaIWJyNsvovOKZdOMyIowdeCXlu73JAV5kG3yMGRUUqWB0XK/nV0CCwR
          /Ibmay4FxFDKIUjvKPLOwRSJNZLJNtYc8m3Y+esCjCeD585IqmJShgHr+HPu44=
        - hbady5qDdEh4ItlgK1c4AZgD4xXe+cBbQZzItrCoaMqvlbkG1YUikAdepApv4C7TzdbY3
          huGXZYKSVkDGg4RdDfsB9qL0MmzD6RmUY/PHXxjeluXeziFPTLombnEUv00wQP1OpEvqN
          ENs9rxFvhfHOFeyeRqX5KEZaMRJ6AcuJNge9Z7IOjG7hYW7u93eOhmNAtxPgcVl+kbAjM
          2JJe/2yRT9db+yTXzjuKy1I3iUF3VX+3rlrld+VTU425/ZfbUjnbROJ/d61HTEgt8m927
          mHRD0RCkZ4R/L9neMC8XLbCnWZ9fL3niNWTcy6A/CBmE0YOveyI7e4PNikedwEj6hO5b+
          Jy7Hfdi1+3EdS/NATFMk+dSgGtxLE4xqXmLe6UMQ/lyfXCFyscN5m4Iwrsxs1jxtrLpkY
          T1RKaosqZhz6Gua+VtKH8dqNHji/qQejNNixBiT7+xmvPIW9SE7JscU2z4E6FPPRUAXFz
          6NkFzv7z5UcmAUAEaR1UZ8T897Dw3EdchFT4D9rNDgmpfU0+9jCzSinCW7bQjn7w/EqMG
          LSNkshIw2nBm0m/IBNTkfgW9+RATme5ow56Sg96rfZ2UkktzkF7B/dbRnu9AdaTX+pQZy
          +e5L3Bfe+aQENZ2P0E7b7WA0h1oMhG5+6gZ/WmOq0gKxdpRGDje/oeAlK+QlCU=
        - aIVQe3AsS2uKl1bthFy40RrVClhV+S7D4kvru7kBNYlmxmriH6t/OsiqOCxnsy+cL1epi
          fQq2106VTQgApiTxGw2TodzSdbcctVYKoy431SUYVhbBTT34JYeJMRHnMVXpylm0RKZJq
          fXjYUiEqMJTwEjEztgZJ3U3ATfurxj76s/9gx+NrFt1xXJxIHsiUpSJUxJlm7Y1WwUfuU
          LXm/I8jyZ15rGXupeoDzKGBFQkwHlztH9GTwi/NW8ue8CubYmldcTRgWMGNYq/p6VCD3W
          zwaXDydHOS0/2CO3QX16OQFe7ODr4IKb6E67ohoExw4sAzeRwdnSesnCdzCXttNI7U6QR
          CXCInpFfNVhP0euimRdDJPZy5hs1liZ5QeSJjtxdl65Hsy/DRSufvnuiywSSJZc9FTIS4
          OMe8oHBxjfhsDDpKg2xDICJlTC0MjVK9j3h5zIsD82WWDK6ThXi+kAOg94A6u5AdV4UeM
          Inm3LRlUhqUUSajXUFc2+KIrKBuVPop1qX/CtBaZJBF6GGGCPj+SghldEXzd7luA94vRC
          0wIgfFChOrdmrTKy1cAmMS87hztW6bdVhBNwXqCQXZwJehsnpwxvU2ZdeId9UrOey3mIJ
          gvFWcSYIJIzopDDemE8I6jgrmTrT6Y3T121kffWKzk0AwMmHOadfKTgMyBVI2c=
        - DMdv73orwDReyNO+Dpb+gaN84KMceQCVgY0rIZ1U6FC2pn85uCTFE5CpaDRSro0GKVZ9z
          LuZXTber4RAjm5/QM4nao+k6cxFY48r1ZZQHIIjsp4KfIG9fU0dcDJJscHO2suI2a1DS6
          zgpD6gr+jfr0Evl1ZeEDHuYoW0BBedeK99w+TVYKptL0wlOcvSg+yPq2k5my4NiAUuWBo
          ++4WaC/zKsI7XjDA15uj8Rj5fOg1nmPb+/Is+5hQlcbV8l5dOkq4sc7TPSdWbmXnguYTS
          vBKO4fChthiTUxhmGi/CdTiWYVIXhnRgPwJ8hLmsQnqJh9Bp8qaSle+rjjLhxg53p3V8N
          WCIQWN2GIzDo4edaeSVm4LZANOak5Y6l0K77dFYwq4ICVxymPt0VPxgKq2HfQrK7Sre9f
          dD9Bwd2xRq1PBh8d9m6wWU1LWUecOCzLOvelFZIbQEKcGFZZBA3uXg91KCyveYFvA0Do7
          l576+GaBHHZQcfWeJo9+x441KwP8/Hu5/VhPO74D5t6VQQPDjISbTSc2S0I6TeCrW2H6s
          ZLWlyEtN83UEBZ+H46CEx/vY5GipBZ+peA9wRhh6kGuOlDTGqfczUEYpC5TKAJ4dfPpmp
          sYW15rzSqyGFB8KwGXCRmlrzTYonulW+rmEMquv6hm68uooseosC9ZSAvsuV1k=

- job:
    name: ara-web-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors recordsansible/ara-web to ansible-community/ara-web
    allowed-projects: recordsansible/ara-web
    vars:
      git_mirror_repository: ansible-community/ara-web
    secrets:
      - name: git_mirror_credentials
        secret: ara_web_git_mirror_credentials
        pass-to-parent: true

- project:
    check:
      jobs:
        - ara-web-unit-tests
        - ara-web-build-dashboard
    gate:
      jobs:
        - ara-web-unit-tests
    post:
      jobs:
        - ara-web-upload-git-mirror
